### ISSUE TITLE
Comparison of mock.call() objects fails with TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#128]
Comparisons of un-equal `mock.call` objects seem to be failing with an internal error.

I'm running this on Python 2.7.9.

```
from mock import call
from testfixtures import compare
compare(call(x='one'), call(x='two'))
```

Results in the following failure:
```
Traceback (most recent call last):
  File "[...]/scratch.py", line 5, in <module>
    compare(call(x='one'), call(x='two'))
  File "[...]/testfixtures/comparison.py", line 608, in compare
    if not context.different(x, y, not_there):
  File "[...]/testfixtures/comparison.py", line 531, in different
    result = comparer(x, y, self)
  File "[...]/testfixtures/comparison.py", line 169, in compare_tuple
    return _compare_mapping(dict(zip(x_fields, x)),
TypeError: unhashable type: 'dict'
```

Looks like it might be related to this feature introduced 6.4.0:

> * Introduce a facade for unittest.mock at testfixtures.mock, including an important bug fix for call() objects.

**Comment by cjw296** [comment]
What version of mock are you using?

```
$ pip freeze | grep mock
mock==2.0.0
$ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mock import call
>>> from testfixtures import compare
>>> compare(call(x=1), call(x=1))
>>> compare(call(x=1), call(x=2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/vcs/git/testfixtures/testfixtures/comparison.py", line 641, in compare
    raise AssertionError(message)
AssertionError: 'call(x=1)' != 'call(x=2)'
```
...and...
```
$ pip freeze | grep mock
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
mock==3.0.5
$ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mock import call
>>> from testfixtures import compare
>>> compare(call(x=1), call(x=1))
>>> compare(call(x=1), call(x=2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/vcs/git/testfixtures/testfixtures/comparison.py", line 641, in compare
    raise AssertionError(message)
AssertionError: 'call(x=1)' != 'call(x=2)'
>>> compare(call(x='one'), call(x='two'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testfixtures/comparison.py", line 641, in compare
    raise AssertionError(message)
AssertionError: 
"call(x='one')"
!=
"call(x='two')"
```

There's also a unit test which covers this case:
https://github.com/Simplistix/testfixtures/blob/master/testfixtures/tests/test_compare.py#L1516-L1540

**Comment by asqui** [comment]
Hmmm, initially I thought this might be because we're on an ancient version of mock, but no... we're on 2.0.0...
```
$ pip freeze | grep mock
mock==2.0.0
```

**Comment by cjw296** [comment]
Yeah, but not to the latest, that no longer supports Python 2 ;-) (you want 3.0.5)

Unfortunately, setup.py has no way to specify "this optional dep needs to be of at least this version". If you know of a way, PRs very welcome...

**Comment by asqui** [comment]
If you know the minimum version of mock that is supported, you could add it as a comment in setup.py -- it won't be enforced, but at least it'll be documented.

But I'm guessing that you don't know where exactly along the road from 1.0.1 to 3.0.5 the problems cease...

**Comment by cjw296** [comment]
I'd always suggest going with the latest possible. The comment won't really help.
