### ISSUE TITLE
Error with Python 3.6.3 and flake8 4.0.1

### ISSUE THREAD

**Issue by selimt** [simplistix/testfixtures#172]
The latest tag of testfixtures (6.18.5) breaks Python 3.6.3 compatibility:

```
flake8
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/usr/local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/flake8_isort.py", line 15, in <module>
    from testfixtures import OutputCapture
  File "/usr/local/lib/python3.6/site-packages/testfixtures/__init__.py", line 13, in <module>
    from testfixtures.comparison import (
  File "/usr/local/lib/python3.6/site-packages/testfixtures/comparison.py", line 14, in <module>
    from testfixtures.mock import parent_name, mock_call, unittest_mock_call
  File "/usr/local/lib/python3.6/site-packages/testfixtures/mock.py", line 47, in <module>
    sys.version_info, backport_version
ImportError: Please upgrade Python (you have sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)) or Mock Backport (You have None)
```
Reverting back to testfixtures 6.18.3 fixes the issue.

**Comment by cjw296** [comment]
The message given is pretty clear. Testfixtures used to ship with moneypatches for bugs in unittest.mock in old versions of Python like 3.6.3, but since Python 3.6 is now [past EOL](https://endoflife.date/python) it no longer does.

You can either install the mock backport, or, much better, upgrade to a supported version of Python.

**Comment by selimt** [comment]
Thank you, we are planning to upgrade to 3.7 soon.
