### ISSUE TITLE
8.3.0: documentation build error 

### ISSUE THREAD

**Issue by wuch-g2v** [simplistix/testfixtures#199]
Documentation buids with exit code 0 but looks like something is wrong 
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.3.7
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://django.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://docs.pytest.org/en/latest/objects.inv...
loading intersphinx inventory from https://sybil.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 18 added, 0 changed, 0 removed
reading sources... [100%] warnings
WARNING: autodoc: failed to import function 'compare_exception_group' from module 'testfixtures.comparison'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/util/inspect.py", line 374, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'testfixtures.comparison' has no attribute 'compare_exception_group'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 209, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 329, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 2844, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.10/site-packages/sphinx/util/inspect.py", line 390, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: compare_exception_group

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-testfixtures.3 { comparing mocking datetime logging streams files exceptions warnings popen django twisted utilities api installation development changes license } done
build succeeded, 1 warning.
```

**Comment by cjw296** [comment]
Where, how and why are you trying to build the documentation?

**Comment by wuch-g2v** [comment]
sphinx is executed from source tree

**Comment by cjw296** [comment]
You need to be on Python 3.12

**Comment by wuch-g2v** [comment]
below shows that python>=3.7 is required.
https://github.com/simplistix/testfixtures/blob/608b0532dbbeb6530d9dacce3a912bcc1dc40a87/setup.py#L37
Please update this field.

**Comment by wuch-g2v** [comment]
BTW 3.7 is already EOSed.
It would be good to bump that to 3.8 and filer all code over `pyupgrade --py38-plus`.

**Comment by cjw296** [comment]
The package can be used on Python 3.7 and above, the documentation, however, requires 3.11 to build
