### ISSUE TITLE
Unable to install testfixtures 4.3.0 from pypi (missing tox.ini in source archive)

### ISSUE THREAD

**Issue by sjagoe** [Simplistix/testfixtures#20]
```python
[nix-shell:~/src]$ pip install -U testfixtures
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.                                                                                                                    
Collecting testfixtures
  Using cached testfixtures-4.3.0.tar.gz
    Traceback (most recent call last):
      File "/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/configparser.py", line 1116, in _unify_values
        sectiondict = self._sections[section]
    KeyError: 'testenv'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/run/user/1000/pip-build-v8n5_qum/testfixtures/setup.py", line 20, in <module>
        for item in config.get('testenv', 'deps').split():
      File "/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/configparser.py", line 754, in get
        d = self._unify_values(section, vars)
      File "/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/configparser.py", line 1119, in _unify_values
        raise NoSectionError(section)
    configparser.NoSectionError: No section: 'testenv'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/configparser.py", line 1116, in _unify_values
        sectiondict = self._sections[section]
    KeyError: 'testenv'
    
    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/run/user/1000/pip-build-v8n5_qum/testfixtures/setup.py", line 20, in <module>
        for item in config.get('testenv', 'deps').split():
      File "/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/configparser.py", line 754, in get
        d = self._unify_values(section, vars)
      File "/nix/store/8pvy2d921wmink4abi41kqybk6q8v0df-python3-3.4.3/lib/python3.4/configparser.py", line 1119, in _unify_values
        raise NoSectionError(section)
    configparser.NoSectionError: No section: 'testenv'
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /run/user/1000/pip-build-v8n5_qum/testfixtures
```

**Comment by srikanth-viswanathan** [comment]
+1

**Comment by cjw296** [comment]
Just pushed a 4.3.2, can you try that?

**Comment by sjagoe** [comment]
Thanks, @cjw296. v4.3.2 installs successfully.
