### ISSUE TITLE
multiple test failures in version 4.3.3

### ISSUE THREAD

**Issue by jlec** [Simplistix/testfixtures#22]
```
======================================================================
ERROR: A unittest suite that processes files with Manuel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib64/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
TypeError: TestSuite() takes at least 1 argument (0 given)

======================================================================
ERROR: test suite for <module 'testfixtures.tests.test_logcapture' from '/var/tmp/portage/dev-python/testfixtures-4.3.3/work/testfixtures-4.3.3-python2_7/testfixtures/tests/test_logcapture.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib64/python2.7/site-packages/nose/util.py", line 469, in try_run
    return func(obj)
  File "/var/tmp/portage/dev-python/testfixtures-4.3.3/work/testfixtures-4.3.3-python2_7/testfixtures/tests/test_logcapture.py", line 367, in setUp
    test.globs['log_capture']=LogCapture()
AttributeError: 'module' object has no attribute 'globs'

======================================================================
ERROR: test suite for <module 'testfixtures.tests.test_manuel_examples' from '/var/tmp/portage/dev-python/testfixtures-4.3.3/work/testfixtures-4.3.3-python2_7/testfixtures/tests/test_manuel_examples.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib64/python2.7/site-packages/nose/util.py", line 469, in try_run
    return func(obj)
  File "/var/tmp/portage/dev-python/testfixtures-4.3.3/work/testfixtures-4.3.3-python2_7/testfixtures/tests/test_manuel_examples.py", line 17, in setUp
    test.globs['tempdir']=TempDirectory()
AttributeError: 'module' object has no attribute 'globs'

======================================================================
ERROR: test suite for <module 'testfixtures.tests.test_tempdirectory' from '/var/tmp/portage/dev-python/testfixtures-4.3.3/work/testfixtures-4.3.3-python2_7/testfixtures/tests/test_tempdirectory.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib64/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib64/python2.7/site-packages/nose/util.py", line 469, in try_run
    return func(obj)
  File "/var/tmp/portage/dev-python/testfixtures-4.3.3/work/testfixtures-4.3.3-python2_7/testfixtures/tests/test_tempdirectory.py", line 332, in setUp
    test.globs['temp_dir']=TempDirectory()
AttributeError: 'module' object has no attribute 'globs'

----------------------------------------------------------------------
Ran 428 tests in 0.265s
```

**Comment by jlec** [comment]
This happens with python 2.7, 3.3 and 3.4

**Comment by cjw296** [comment]
I'm afraid Travis doesn't agree: 
https://travis-ci.org/Simplistix/testfixtures

How have you set up your development environment?
Please follow the instructions here and let me know:

http://testfixtures.readthedocs.org/en/latest/development.html

**Comment by jlec** [comment]
I saw that travis is fine for you. I cam packaging this for a downstream distro. Any idea where the problem could come from?

**Comment by cjw296** [comment]
How are you setting up your test environment?

**Comment by jlec** [comment]
```
python setup.py build
PYTHONPATH=build/lib nosetests
```

**Comment by jlec** [comment]
I was missing mock_fixes. Sorry for the noise

**Comment by cjw296** [comment]
I would, however, recommend running the tests as described in the development section.
All the deps for build and test are listed in setup.py.

**Comment by jlec** [comment]
We need to test it during the installation as close to what our users get through the package manager.

**Comment by cjw296** [comment]
Then, I'm afraid, you can expect problems...

Out of curiosity, which downstream package is this?

**Comment by jlec** [comment]
That's for Gentoo Linux.
