### ISSUE TITLE
LogCapture persists records between parent and child tests

### ISSUE THREAD

**Issue by kreativitea** [Simplistix/testfixtures#42]
When attempting to capture during a unittest that uses subclassing, the tests fail due to LogCapture maintaining records between two logically distinct test cases.  

```python
from unittest import TestCase
import logging
from testfixtures import log_capture

logger = logging.getLogger(__file__)

class FixtureTest(TestCase):
    @log_capture(level=logging.ERROR)
    def test_my_fixture(self, capture):
        log_single_error()
        self.assertEqual(len(capture.records), 1, capture.records)

class FixtureSubclassTest(TestFixtureSanity):
    pass
    # test_my_fixture is invoked when this TestCase is run through inheritance

def log_single_error():
    logger.error('my awesome error')
```

```
.F
======================================================================
FAIL: test_my_fixture (redacted.common.clients.tests.test_fixture_bug.TestFixtureSubclass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mycomputer/Documents/Code/redacted/current/web/env.d/lib/python2.7/site-packages/testfixtures/utils.py", line 44, in wrapping
    return wrapped(*args, **kw)
  File "/Users/mycomputer/Documents/Code/elacarte/current/web/redacted/common/clients/tests/test_fixture_bug.py", line 12, in test_my_fixture
    self.assertEqual(len(capture.records), 1, capture.records)
AssertionError: [<logging.LogRecord object at 0x10b4acd90>, <logging.LogRecord object at 0x10b4acf10>]

----------------------------------------------------------------------
Ran 2 tests in 0.001s
```

Note the pair of objects reported by the AssertionError.

**Comment by cjw296** [comment]
Two things:

- your base class shouldn't mix in TestCase unless you want it to be run as a test.

- no decorator can behave as you expect, use [this pattern](http://testfixtures.readthedocs.io/en/latest/logging.html#the-context-manager) instead.

**Comment by kreativitea** [comment]
That's the idea, I do want it to be run as a test.  I'll give the contextmanager a shot.
