### ISSUE TITLE
@log_capture doesn't work for test methods with python2.7

### ISSUE THREAD

**Issue by gganssauge** [Simplistix/testfixtures#63]
The following testcase doesn't run:
```
import unittest

from testfixtures import log_capture


class MyTestCase(unittest.TestCase):
    @log_capture
    def test_something(self, l):
        self.assertEqual(True, True)


if __name__ == '__main__':
    unittest.main()
```

Starting the test fails with
```
Error in test test_something (Products.CRSReady.tests.test_log_catpure.MyTestCase)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/gotti/source/CRS/workspace/crs/src/Products.CRSReady/eggs/testfixtures-4.14.3-py2.7.egg/testfixtures/utils.py", line 33, in wrapper
    @wraps(wrapped)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'MyTestCase' object has no attribute '__name__'

  Ran 1 tests with 0 failures, 1 errors and 0 skipped in 0.001 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```

I'm using Python-2.7.12 on Ubuntu-16.04

**Comment by cjw296** [comment]
You're missing some parentheses:

http://testfixtures.readthedocs.io/en/latest/logging.html#the-decorator

**Comment by gganssauge** [comment]
:facepalm: - thanks
